[project]
name = "crawl4ai-mcp-py"
version = "0.1.0"
description = "Minimum MCP server to convert web2md"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.7.4",
    "playwright-stealth>=2.0.0",
]
